### Nominal / OHE Onehotencoder Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
#create a sample dataframe with a categorical variables
df = pd.DataFrame({
    'color': ['red','blue','green','green','red','blue']
})

In [3]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [4]:
# create an instance of the One hot encoder
encoder = OneHotEncoder()

In [5]:
# fit the encoder to the dataframe and transform the categorical variables
encoded = encoder.fit_transform(df[['color']])

In [6]:
import pandas as pd 
encoded_df = pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [7]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red'], dtype=object)

In [8]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [9]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [10]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [11]:
import seaborn as sns